#ifndef __CONFIG_H
#define __CONFIG_H

#define CFG_EXPANDTABS   TRUE
#define CFG_TABWIDTH     4
#define CFG_IGNORECASE   TRUE
#define CFG_LINENUMBER   TRUE
#define CFG_PICKERPATH   STATUS_FILEPATH
#define CFG_STATUSPATH   STATUS_FILENAME
#define CFG_ATTRSTATUS   A_BOLD
#define CFG_ATTRLINENO   A_DIM
#define CFG_ATTRCURLINE  A_BOLD
#define CFG_ATTRSELECT   A_REVERSE|A_BOLD
#define CFG_ATTRUNSELECT A_DIM

#endif
