#ifndef __CONFIG_H
#define __CONFIG_H

#define CFG_EXPANDTABS   TRUE
#define CFG_TABWIDTH     4
#define CFG_IGNORECASE   TRUE
#define CFG_LINENUMBER   FALSE
#define CFG_INVERTSTATUS TRUE
#define CFG_STATUSPATH   STATUS_FILENAME
#define CFG_PICKERPATH   STATUS_FILEPATH

#endif
