.Dd May 15, 2026
.Dt LED 1
.Sh NAME
.Nm led
.Nd tiny text editor
.Sh SYNOPSIS
.Nm
.Op Fl CcEeLlRrhv
.Op Fl t Ar tab_size
.Op Ar files...
.Sh DESCRIPTION
.Nm
is a lightweight text editor for the terminal.
The statusbar is formatted as
.B
COL LINE:SIZE (CUR:BUFS FILE)
as follows:
.Bl -tag -width indent
.It COL  Is the current cursor column.
.It LINE Is the current cursor line.
.It SIZE Is the number of lines in the current buffer.
.It CUR  Is the current buffer.
.It BUFS Is the number of open buffers.
.It FILE Is the name of the current buffer.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl C
Enables case-insensitive search.
.It Fl c
Disables case-insensitive search.
.It Fl E
Enables expanding tabs to spaces.
.It Fl e
Disables expanding tabs to spaces.
.It Fl L
Enables line numbers.
.It Fl l
Disables line numbers.
.It Fl R
Enables read-only mode.
.It Fl r
Disables read-only mode.
.It Fl h
Prints help message and exits.
.It Fl v
Prints version and exits.
.It Fl t Ar tab_size
Sets the number of spaces used to draw tabs.
.Sh KEYBINDS
.Bl -tag -width indent
.It Ctrl+s
Save the current buffer to a file.
.It Ctrl+o
Open file picker.
.It Ctrl+b
Open the buffer selector.
.It Ctrl+w
Switch to next buffer.
.It Ctrl+z
Undo change.
.It Ctrl+y
Redo change.
.It Ctrl+q
Close buffer.
.It Ctrl+f
Enter search mode.
.It Ctrl+r
Enter replace mode when searching.
.It Ctrl+n
Go to next search match.
.It Ctrl+g
Go to line.
.It Ctrl+c
Copy line/selection.
.It Ctrl+x
Cut line/selection.
.It Ctrl+v
Paste text.
.It Ctrl+{Left,Right}
Move whole word backward/forward.
.It Ctrl+{Backspace,Delete}
Delete whole word backward/forward.
.It Tab
Indent current line/selection.
.It Shift+Tab
Unindent current line/selection.
.Sh KEYBINDS (FILE PICKER)
.Bl -tag -width indent
.It m
Rename current file.
.It c
Copy current file.
.It d
Delete current file.
.It n
Create new file/directory.
.It Ctrl+f
Enter search mode.
.It Ctrl+n
Go to next search match.
.Sh SEE ALSO
.Xr ncurses 3
.Xr xsel 1
.Sh AUTHORS
.An Miu Aq Mt https://github.com/miublue
.Sh BUGS
Probably.
Check 
.Mt https://github.com/miublue/led
and grep for `XXX` to see known issues and missing features.
